require_relative 'node'

Kevin_Bacon = Node.new("Kevin Bacon")
Bill_Murray = Node.new("Bill Murray")
Ernie_Hudson = Node.new("Ernie Hudson")
Michael_McKean = Node.new("Michael Mckean")
Evan_Rachel_Wood = Node.new("Evan Rachel Wood")
Paul_Giamatti = Node.new("Paul Giamatti")
Renee_Zellweger = Node.new("Renee Zellweger")
Natalie_Portman = Node.new("Natalie Portman")
Lori_Singer = Node.new("Lori Singer")
John_Lithgow = Node.new("John Lithgow")
Dianne_Wiest = Node.new("Dianne Wiest")
Chris_Penn = Node.new("Chris Penn")
Sarah_Jessica_Parker = Node.new("Sarah Jessica Parker")
Matt_Dillon = Node.new("Matt Dillon")
Neve_Campbell = Node.new("Neve Campbell")
Theresa_Russell = Node.new("Theresa Russell")
Denise_Richards = Node.new("Denise Richards")
Dan_Aykroyd = Node.new("Dan Aykroyd")
Sigourney_Weaver = Node.new("Sigourney Weaver")
Chevy_Chase = Node.new("Chevy Chase")
Rodney_Dangerfield = Node.new("Rodney Dangerfield")
Ted_Knight = Node.new("Ted Knight")
Brendan_Fraser = Node.new("Brendan Fraser")
Judd_Nelson = Node.new("Judd Nelson")
Larry_David = Node.new("Larry David")
Samantha_Bee = Node.new("Samantha Bee")
Clint_Eastwood = Node.new("Clint Eastwood")
Isaiah_Washington = Node.new("Isaiah Washington")
James_Woods = Node.new("James Woods")
Mickey_Rourke = Node.new("Mickey Rourke")
Marisa_Tomei = Node.new("Marisa Tomei")
Todd_Barry = Node.new("Todd Barry")
Ryan_Gosling = Node.new("Ryan Gosling")
George_Clooney = Node.new("George Clooney")
Russell_Crowe = Node.new("Russell Crowe")
Rosemarie_DeWitt = Node.new("Rosemarie DeWitt")
Tom_Cruise = Node.new("Tom Cruise")
Kelly_Preston = Node.new("Kelly Preston")
Bonnie_Hunt = Node.new("Bonnie Hunt")
Jude_Law = Node.new("Jude Law")
Nicole_Kidman = Node.new("Nicole Kidman")
Julia_Roberts = Node.new("Julia Roberts")
Clive_Owen = Node.new("Clive Owen")
Mila_Kunis = Node.new("Mila Kunis")
Winona_Ryder = Node.new("Winona Ryder")
Barbara_Hershey =  Node.new("Barbara Hershey")
Kathy_Bates = Node.new("Kathy Bates")
Anthony_Edwards = Node.new("Anthony Edwards")
Leonardo_DiCaprio = Node.new("Leonardo DiCaprio")
Kate_Winslet = Node.new("Kate Winslet")
Joseph_Gordon_Levitt = Node.new("Joseph Gordon-Levitt")
Ellen_Page = Node.new("Ellen Page")
Tim_Robbins = Node.new("Tim Robbins")
Meg_Ryan = Node.new("Meg Ryan")
Denzel_Washington = Node.new("Denzel Washington")
Stanley_Tucci = Node.new("Stanley Tucci")
Jodie_Foster = Node.new("Jodie Foster")
Willem_Dafoe = Node.new("Willem Dafoe")
Brad_Pitt = Node.new("Brad Pitt")
Michael_Caine = Node.new("Michael Caine")
Woody_Allen = Node.new("Woody Allen")
Steve_Martin = Node.new("Steve Martin")
Glenne_Headley = Node.new("Glenn Headley")
Scarlett_Johansson = Node.new("Scarlett Johansson")
Julianne_Moore = Node.new("Julianne Moore")
Christian_Slater = Node.new("Christian Slater")
Patricia_Arquette = Node.new("Patricia Arquette")
Matthew_McConaughey = Node.new("Matthew McConaughey")
Anne_Hathaway = Node.new("Anne Hathaway")

Kevin_Bacon.film_actor_hash['Footloose']             = [ Lori_Singer, John_Lithgow, Dianne_Wiest, Chris_Penn, Sarah_Jessica_Parker ]
Kevin_Bacon.film_actor_hash['Wild Things']           = [ Matt_Dillon, Neve_Campbell, Bill_Murray ]
Bill_Murray.film_actor_hash['Wild Things']           = [ Matt_Dillon, Neve_Campbell, Kevin_Bacon ]
Neve_Campbell.film_actor_hash['Wild Things']         = [ Matt_Dillon, Bill_Murray, Kevin_Bacon ]
Matt_Dillon.film_actor_hash['Wild Things']           = [ Bill_Murray, Neve_Campbell, Kevin_Bacon ]
Bill_Murray.film_actor_hash['Ghostbusters']          = [ Dan_Aykroyd, Sigourney_Weaver, Ernie_Hudson ]
Bill_Murray.film_actor_hash['Caddyshack']            = [ Chevy_Chase, Rodney_Dangerfield, Ted_Knight ]
Chevy_Chase.film_actor_hash['Caddyshack']            = [ Bill_Murray, Rodney_Dangerfield, Ted_Knight ]
Rodney_Dangerfield.film_actor_hash['Caddyshack']     = [ Chevy_Chase, Bill_Murray, Ted_Knight ]
Ted_Knight.film_actor_hash['Caddyshack']             = [ Chevy_Chase, Rodney_Dangerfield, Bill_Murray ]
Ernie_Hudson.film_actor_hash['Airheads']             = [ Brendan_Fraser, Michael_McKean, Judd_Nelson]
Brendan_Fraser.film_actor_hash['Airheads']           = [ Ernie_Hudson, Michael_McKean, Judd_Nelson]
Judd_Nelson.film_actor_hash['Airheads']              = [ Brendan_Fraser, Michael_McKean, Ernie_Hudson]
Ernie_Hudson.film_actor_hash['Ghostbusters']         = [ Dan_Aykroyd, Sigourney_Weaver, Bill_Murray ]
Dan_Aykroyd.film_actor_hash['Ghostbusters']          = [ Ernie_Hudson, Sigourney_Weaver, Bill_Murray ]
Sigourney_Weaver.film_actor_hash['Ghostbusters']     = [ Dan_Aykroyd, Ernie_Hudson, Bill_Murray ]
Michael_McKean.film_actor_hash['Airheads']           = [ Brendan_Fraser, Ernie_Hudson, Judd_Nelson]
Michael_McKean.film_actor_hash['Whatever Works']     = [ Larry_David, Samantha_Bee, Evan_Rachel_Wood ]
Larry_David.film_actor_hash['Whatever Works']        = [ Michael_McKean, Samantha_Bee, Evan_Rachel_Wood ]
Evan_Rachel_Wood.film_actor_hash['Whatever Works']   = [ Larry_David, Samantha_Bee, Michael_McKean ]
Samantha_Bee.film_actor_hash['Whatever Works']       = [ Larry_David, Michael_McKean, Evan_Rachel_Wood ]
Michael_McKean.film_actor_hash['True Crime']         = [ Clint_Eastwood, Isaiah_Washington, James_Woods ]
Clint_Eastwood.film_actor_hash['True Crime']         = [ Michael_McKean, Isaiah_Washington, James_Woods ]
Isaiah_Washington.film_actor_hash['True Crime']      = [ Clint_Eastwood, Michael_McKean, James_Woods ]
James_Woods.film_actor_hash['True Crime']            = [ Clint_Eastwood, Isaiah_Washington, Michael_McKean ]
Evan_Rachel_Wood.film_actor_hash['The Wrestler']     = [ Mickey_Rourke, Marisa_Tomei, Todd_Barry ]
Mickey_Rourke.film_actor_hash['The Wrestler']        = [ Evan_Rachel_Wood, Marisa_Tomei, Todd_Barry ]
Marisa_Tomei.film_actor_hash['The Wrestler']         = [ Mickey_Rourke, Evan_Rachel_Wood, Todd_Barry ]
Todd_Barry.film_actor_hash['The Wrestler']           = [ Mickey_Rourke, Marisa_Tomei, Evan_Rachel_Wood ]
Evan_Rachel_Wood.film_actor_hash['The Ides of March']= [ Ryan_Gosling, George_Clooney, Paul_Giamatti ]
Ryan_Gosling.film_actor_hash['The Ides of March']    = [ Evan_Rachel_Wood, George_Clooney, Paul_Giamatti ]
George_Clooney.film_actor_hash['The Ides of March']  = [ Ryan_Gosling, Evan_Rachel_Wood, Paul_Giamatti ]
Paul_Giamatti.film_actor_hash['The Ides of March']   = [ Ryan_Gosling, George_Clooney, Evan_Rachel_Wood ]
Paul_Giamatti.film_actor_hash['Cinderella Man']      = [ Russell_Crowe, Renee_Zellweger, Rosemarie_DeWitt ]
Russell_Crowe.film_actor_hash['Cinderella Man']      = [ Paul_Giamatti, Renee_Zellweger, Rosemarie_DeWitt ]
Renee_Zellweger.film_actor_hash['Cinderella Man']    = [ Russell_Crowe, Paul_Giamatti, Rosemarie_DeWitt ]
Rosemarie_DeWitt.film_actor_hash['Cinderella Man']   = [ Russell_Crowe, Renee_Zellweger, Paul_Giamatti ]
Renee_Zellweger.film_actor_hash['Jerry Maguire']     = [ Tom_Cruise, Kelly_Preston, Bonnie_Hunt ]
Tom_Cruise.film_actor_hash['Jerry Maguire']          = [ Renee_Zellweger, Kelly_Preston, Bonnie_Hunt ]
Kelly_Preston.film_actor_hash['Jerry Maguire']       = [ Tom_Cruise, Renee_Zellweger, Bonnie_Hunt ]
Bonnie_Hunt.film_actor_hash['Jerry Maguire']         = [ Tom_Cruise, Kelly_Preston, Renee_Zellweger ]
Renee_Zellweger.film_actor_hash['Cold Mountain']     = [ Jude_Law, Nicole_Kidman, Natalie_Portman ]
Nicole_Kidman.film_actor_hash['Cold Mountain']       = [ Jude_Law, Renee_Zellweger, Natalie_Portman ]
Natalie_Portman.film_actor_hash['Closer']            = [ Julia_Roberts, Jude_Law, Clive_Owen ]
Clive_Owen.film_actor_hash['Closer']                 = [ Julia_Roberts, Jude_Law, Natalie_Portman ]
Jude_Law.film_actor_hash['Closer']                   = [ Julia_Roberts, Clive_Owen, Natalie_Portman ]
Natalie_Portman.film_actor_hash['Black Swan']        = [ Mila_Kunis, Winona_Ryder, Barbara_Hershey]
Mila_Kunis.film_actor_hash['Black Swan']             = [ Natalie_Portman, Winona_Ryder, Barbara_Hershey]
Lori_Singer.film_actor_hash['Footloose']             = [ Kevin_Bacon, John_Lithgow, Dianne_Wiest, Chris_Penn, Sarah_Jessica_Parker ]
Lori_Singer.film_actor_hash['Summer Heat']           = [ Kathy_Bates, Anthony_Edwards ]
Kathy_Bates.film_actor_hash['Summer Heat']           = [ Lori_Singer, Anthony_Edwards ]
Kathy_Bates.film_actor_hash['Titanic']               = [ Leonardo_DiCaprio, Kate_Winslet ]
Leonardo_DiCaprio.film_actor_hash['Titanic']         = [ Kathy_Bates, Kate_Winslet ]
Leonardo_DiCaprio.film_actor_hash['Inception']       = [ Joseph_Gordon_Levitt, Ellen_Page ]
Joseph_Gordon_Levitt.film_actor_hash['Inception']    = [ Leonardo_DiCaprio, Ellen_Page ]
Joseph_Gordon_Levitt.film_actor_hash['Don Jon']      = [ Scarlett_Johansson, Glenne_Headley ]
Ellen_Page.film_actor_hash['Inception']              = [ Joseph_Gordon_Levitt, Leonardo_DiCaprio ]
Kate_Winslet.film_actor_hash['Titanic']              = [ Leonardo_DiCaprio, Kathy_Bates ]
Anthony_Edwards.film_actor_hash['Summer Heat']       = [ Kathy_Bates, Lori_Singer ]
Anthony_Edwards.film_actor_hash['Top Gun']           = [ Tom_Cruise, Tim_Robbins, Meg_Ryan ]
Tim_Robbins.film_actor_hash['Top Gun']               = [ Tom_Cruise, Anthony_Edwards, Meg_Ryan ]
Meg_Ryan.film_actor_hash['Top Gun']                  = [ Tom_Cruise, Tim_Robbins, Anthony_Edwards ]
Tom_Cruise.film_actor_hash['Top Gun']                = [ Meg_Ryan, Tim_Robbins, Anthony_Edwards ]
John_Lithgow.film_actor_hash['Footloose']            = [ Lori_Singer, Kevin_Bacon, Dianne_Wiest, Chris_Penn, Sarah_Jessica_Parker ]
John_Lithgow.film_actor_hash['The Pelican Brief']    = [ Julia_Roberts, Denzel_Washington, Stanley_Tucci ]
Stanley_Tucci.film_actor_hash['The Pelican Brief']   = [ Julia_Roberts, Denzel_Washington, John_Lithgow ]
Julia_Roberts.film_actor_hash['Oceans Eleven']       = [ George_Clooney, Brad_Pitt ]
George_Clooney.film_actor_hash['Oceans Eleven']      = [ Julia_Roberts, Brad_Pitt ]
Denzel_Washington.film_actor_hash['Inside Man']      = [ Jodie_Foster, Clive_Owen, Willem_Dafoe ]
Jodie_Foster.film_actor_hash['Inside Man']           = [ Denzel_Washington, Clive_Owen, Willem_Dafoe ]
Willem_Dafoe.film_actor_hash['Inside Man']           = [ Jodie_Foster, Clive_Owen, Denzel_Washington ]
Dianne_Wiest.film_actor_hash['Footloose']            = [ Lori_Singer, John_Lithgow, Kevin_Bacon, Chris_Penn, Sarah_Jessica_Parker ]
Dianne_Wiest.film_actor_hash['Hannah and Her Sisters'] = [ Barbara_Hershey, Michael_Caine, Woody_Allen ]
Barbara_Hershey.film_actor_hash['Hannah and Her Sisters'] = [ Dianne_Wiest, Michael_Caine, Woody_Allen ]
Woody_Allen.film_actor_hash['Hannah and Her Sisters'] = [ Dianne_Wiest, Michael_Caine, Barbara_Hershey ]
Michael_Caine.film_actor_hash['Dirty Rotten Scoundrels']  = [ Steve_Martin, Glenne_Headley ]
Glenne_Headley.film_actor_hash['Don Jon']            = [ Joseph_Gordon_Levitt, Scarlett_Johansson, Julianne_Moore ]
Scarlett_Johansson.film_actor_hash['Don Jon']        = [ Joseph_Gordon_Levitt, Glenne_Headley, Julianne_Moore ]
Julianne_Moore.film_actor_hash['Don Jon']            = [ Joseph_Gordon_Levitt, Scarlett_Johansson, Glenne_Headley ]
Chris_Penn.film_actor_hash['Footloose']              = [ Lori_Singer, John_Lithgow, Dianne_Wiest, Kevin_Bacon, Sarah_Jessica_Parker ]
Chris_Penn.film_actor_hash['True Romance']           = [ Brad_Pitt, Christian_Slater, Patricia_Arquette ]
Brad_Pitt.film_actor_hash['True Romance']            = [ Chris_Penn, Christian_Slater, Patricia_Arquette ]
Patricia_Arquette.film_actor_hash['True Romance']    = [ Chris_Penn, Christian_Slater, Brad_Pitt ]
Christian_Slater.film_actor_hash['True Romance']     = [ Chris_Penn, Brad_Pitt, Patricia_Arquette ]
Sarah_Jessica_Parker.film_actor_hash['Footloose']    = [ Lori_Singer, John_Lithgow, Dianne_Wiest, Chris_Penn, Kevin_Bacon ]
Sarah_Jessica_Parker.film_actor_hash['Failure to Launch'] = [ Kathy_Bates, Matthew_McConaughey ]
Matthew_McConaughey.film_actor_hash['Failure to Launch']  = [ Kathy_Bates, Sarah_Jessica_Parker ]
Matthew_McConaughey.film_actor_hash['Interstellar']  = [ Michael_Caine, John_Lithgow, Anne_Hathaway ]
Anne_Hathaway.film_actor_hash['Interstellar']        = [ Michael_Caine, John_Lithgow, Matthew_McConaughey ]

actors_hash = {
  Kevin_Bacon => Kevin_Bacon,
  Bill_Murray => Bill_Murray,
  Ernie_Hudson => Ernie_Hudson,
  Michael_McKean => Michael_McKean,
  Evan_Rachel_Wood => Evan_Rachel_Wood,
  Paul_Giamatti => Paul_Giamatti,
  Renee_Zellweger => Renee_Zellweger,
  Natalie_Portman => Natalie_Portman,
  Lori_Singer => Lori_Singer,
  John_Lithgow => John_Lithgow,
  Dianne_Wiest => Dianne_Wiest,
  Chris_Penn => Chris_Penn,
  Sarah_Jessica_Parker => Sarah_Jessica_Parker,
  Matt_Dillon => Matt_Dillon,
  Neve_Campbell => Neve_Campbell,
  Theresa_Russell => Theresa_Russell,
  Denise_Richards => Denise_Richards,
  Dan_Aykroyd => Dan_Aykroyd,
  Sigourney_Weaver => Sigourney_Weaver,
  Chevy_Chase => Chevy_Chase,
  Rodney_Dangerfield => Rodney_Dangerfield,
  Ted_Knight => Ted_Knight,
  Brendan_Fraser => Brendan_Fraser,
  Judd_Nelson => Judd_Nelson,
  Larry_David => Larry_David,
  Samantha_Bee => Samantha_Bee,
  Clint_Eastwood => Clint_Eastwood,
  Isaiah_Washington => Isaiah_Washington,
  James_Woods => James_Woods,
  Mickey_Rourke => Mickey_Rourke,
  Marisa_Tomei => Marisa_Tomei,
  Todd_Barry => Todd_Barry,
  Ryan_Gosling => Ryan_Gosling,
  George_Clooney => George_Clooney,
  Russell_Crowe => Russell_Crowe,
  Rosemarie_DeWitt => Rosemarie_DeWitt,
  Tom_Cruise => Tom_Cruise,
  Kelly_Preston => Kelly_Preston,
  Bonnie_Hunt => Bonnie_Hunt,
  Jude_Law => Jude_Law,
  Nicole_Kidman => Nicole_Kidman,
  Julia_Roberts => Julia_Roberts,
  Clive_Owen => Clive_Owen,
  Mila_Kunis => Mila_Kunis,
  Winona_Ryder => Winona_Ryder,
  Barbara_Hershey => Barbara_Hershey,
  Kathy_Bates => Kathy_Bates,
  Anthony_Edwards => Anthony_Edwards,
  Leonardo_DiCaprio => Leonardo_DiCaprio,
  Kate_Winslet => Kate_Winslet,
  Joseph_Gordon_Levitt => Joseph_Gordon_Levitt,
  Ellen_Page => Ellen_Page,
  Tim_Robbins => Tim_Robbins,
  Meg_Ryan => Meg_Ryan,
  Denzel_Washington => Denzel_Washington,
  Stanley_Tucci => Stanley_Tucci,
  Jodie_Foster => Jodie_Foster,
  Willem_Dafoe => Willem_Dafoe,
  Brad_Pitt => Brad_Pitt,
  Michael_Caine => Michael_Caine,
  Woody_Allen => Woody_Allen,
  Steve_Martin => Steve_Martin,
  Glenne_Headley => Glenne_Headley,
  Scarlett_Johansson => Scarlett_Johansson,
  Julianne_Moore => Julianne_Moore,
  Christian_Slater => Christian_Slater,
  Patricia_Arquette => Patricia_Arquette,
  Matthew_McConaughey => Matthew_McConaughey,
  Anne_Hathaway => Anne_Hathaway
}
